-- Task (Q143): For inventory records of inactive products, set reorder_point to quantity_on_hand plus 10. Return warehouse_id, product_id, quantity_on_hand, and reorder_point for each updated inventory record.
-- Requirement: No ordering is required.
