-- Task (Q083): Return product_id, product_name, category_id, and unit_price for active products whose unit_price is at least as high as every other active product in the same category. Include ties.
-- Requirement: Order by category_id ascending, then product_id ascending.
