-- Task (Q085): Return supplier_id, supplier_name, product_id, product_name, and unit_price for active products whose unit_price is at least as high as every other active product from the same supplier. Include only suppliers with at least two active products, and include ties.
-- Requirement: Order by supplier_id ascending, then product_id ascending.
