-- Task (Q119): Return product_id, sku, and name for active products that are available in at least one warehouse with positive quantity_on_hand or in at least one store with positive quantity_on_hand. Include each qualifying product once.
-- Requirement: Order by product_id ascending.
