-- Task (Q075): Return order_id, ordered_at, customer_id, customer_first_name, customer_last_name, and order_item_count for orders placed by customers who have also submitted at least one review with a rating of 5. Include only orders containing at least two line items.
-- Requirement: Order by ordered_at descending, then order_id descending.
