-- Task (Q068): Return supplier_id, supplier_name, product_id, product_name, and unit_price for active products from suppliers that also supply at least one other active product priced above 1,000.00.
-- Requirement: Order by supplier_id ascending, then product_id ascending.
