-- Task (Q070): Return warehouse_id, warehouse_code, product_id, sku, quantity_on_hand, and reorder_point for inventory rows that are at or below their reorder point and have no matching store_inventory row with a positive quantity_on_hand for the same product.
-- Requirement: Order by warehouse_id ascending, then product_id ascending.
