-- Task (Q077): Return payment_id, order_id, payment_method, amount, and status for payments whose payment_method is used by at least one failed payment.
-- Requirement: Order by payment_id ascending.
