-- Task (Q080): Return supplier_id, supplier_name, and active_product_count for suppliers with at least two active products, where at least one active product costs more than any active product in category_id 1.
-- Requirement: Order by active_product_count descending, then supplier_id ascending.
